const WIDTH_HEALTHBAR_SHIP = 128;

var Container = PIXI.Container,
		autoDetectRenderer = PIXI.autoDetectRenderer,
		loader = PIXI.loader,
		resources = PIXI.loader.resources,
		Sprite = PIXI.Sprite,
		Text = PIXI.Text,
		Graphics = PIXI.Graphics;
			
var ship,
		background10,
		background11,
		background20,
		background21,
		shoot;
		
var	healthBar,
		innerBar,
		outerBar,
		message,
		messageSpeed,
		messageAmmo,
		messageWave,
		messageEnnemiesDestroy,
		messageFin,
		messageBoss,
		messageProtection,
		health,
		ammo,
		protection,
		wave,
		speed,
		damage,
		IDSpawn,
		renderer,
		stage;

var nbSoldiersMax,
		nbSoldiersDestroy,	
		nbSoldiersDestroyStageUp,	
		nbSoldiersDestroyNext,	
		soldierEnnemyHealthArray = [],
		soldierEnnemyDamageArray = [],
		soldierEnnemySpeedArray = [],
		soldierEnnemyHealthBarArray = [],
		soldierEnnemyRandomArray = [],
		soldierEnnemyMaxArray = [],
		soldierEnnemyNumberOfArray = [],
		bossEnnemyHealthArray = [],
		bossEnnemyDamageArray = [],
		bossEnnemySpeedArray = [],
		bossEnnemyHealthBarArray = [],
		bossEnnemyNameArray = [],
		randomBonus,
		waveType,
		messageWageUp,
		IDWageUp,
		IDBonus,
		bonusByWaveMax,
		bonusByWave,
		bossWave,
		bossEndWave;
		
var shootsArray = [],
		shootsEnnemyArray = [],
		soldierEnnemy1Array = [],
		soldierEnnemy2Array = [],
		soldierEnnemy3Array = [],
		soldierEnnemy4Array = [],
		soldierEnnemy5Array = [],
		soldierEnnemy6Array = [],
		soldierEnnemy7Array = [],
		soldierEnnemy8Array = [],
		soldierEnnemy9Array = [],
		soldierEnnemy10Array = [],
		bonusArray = [],
		bossEnnemy;

var numberOfSoldiers;